name: Rust
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/dependabot.yml'
    branches: [develop]
jobs:
  build:
    strategy:
      matrix:
        make_target: ["check-licenses", "build", "integ"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          .cargo
          target
        # you can edit the .github/cache_bust file if you need to clear the cache
        key: ${{ hashFiles('.github/cache_bust') }}-${{ runner.os }}-${{ matrix.make_target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ hashFiles('.github/cache_bust') }}-${{ runner.os }}-${{ matrix.make_target }}-
    - run: rustup update stable
    - run: make ${{ matrix.make_target }}
